apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: controller-manager
  namespace: system
spec:
  ports:
  - name: dhcp
    port: 67
    protocol: UDP
    targetPort: 1067
  selector:
    control-plane: controller-manager
  type: LoadBalancer
