# permissions for end users to view optionsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: optionset-viewer-role
rules:
- apiGroups:
  - dhcp.beryju.org
  resources:
  - optionsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dhcp.beryju.org
  resources:
  - optionsets/status
  verbs:
  - get
