# permissions for end users to view scopes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scope-viewer-role
rules:
- apiGroups:
  - dhcp.beryju.org
  resources:
  - scopes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dhcp.beryju.org
  resources:
  - scopes/status
  verbs:
  - get
